dist: xenial
language: ruby
gemfile: ci/Gemfile
env:
  - ACTIVE_SUPPORT=true
  - NO_ACTIVE_SUPPORT=true
  - ACTIVE_SUPPORT=true FARADAY_VERSION=0.17
  - NO_ACTIVE_SUPPORT=true FARADAY_VERSION=0.17
  # Faraday < 0.9.0 doesn't support the new error class format
  - ACTIVE_SUPPORT=true FARADAY_VERSION=0.8.0
  - NO_ACTIVE_SUPPORT=true FARADAY_VERSION=0.8.0
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
before_install:
   - gem install bundler -v '~> 1.17'
