dist: bionic
language: ruby
before_install:
   - gem install bundler
jobs:
  include:
    - name: "2.4 tests"
      rvm: 2.4.10
      script: ./test.sh
    - name: "2.5 tests"
      rvm: 2.5.8
      script: ./test.sh
    - name: "2.6 tests"
      rvm: 2.6.6
      script: ./test.sh
    - name: "2.7 tests"
      rvm: 2.7.1
      script: ./test.sh
    - name: "Lint"
      rvm: 2.7.1
      script: bundle exec rubocop
