name: Create Release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup ENV
      id: custom-env
      run: |
        export CIRCUITBOX_VERSION=$(echo ${RELEASE_TAG#refs/tags/} | cut -c2-)
        echo "gem_filename=circuitbox-${CIRCUITBOX_VERSION}.gem" >> $GITHUB_OUTPUT

        if echo $CIRCUITBOX_VERSION | grep -q "pre"
        then
          echo "gem_prerelease=true" >> $GITHUB_OUTPUT
        else
          echo "gem_prerelease=false" >> $GITHUB_OUTPUT
        fi
      env:
        RELEASE_TAG: ${{ github.ref }}
    - name: Build Gem
      run: |
        gem build circuitbox.gemspec
        test -f ${{ steps.custom-env.outputs.gem_filename }}
    - name: Generate Sha256sum
      run: |
        shasum -a 256 ${{ steps.custom-env.outputs.gem_filename }} > SHASUMS256.txt
        cat SHASUMS256.txt
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: ${{ steps.custom-env.outputs.gem_prerelease }}
    - name: Upload Gem
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.custom-env.outputs.gem_filename }}
        asset_name: ${{ steps.custom-env.outputs.gem_filename }}
        asset_content_type: application/x-tar
    - name: Upload SHASUMS256.txt
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./SHASUMS256.txt
        asset_name: SHASUMS256.txt
        asset_content_type: text/plain
